name: timetrailblazer
description: "TimeTrailblazer - L'app essenziale per tracciare i tuoi orari di lavoro."
publish_to: 'none'
version: 0.5.0

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  csv: ^6.0.0
  equatable: ^2.0.5
  file_picker: ^8.0.0+1
  flutter_bloc: ^8.1.5
  intl: ^0.19.0
  logger: ^2.2.0
  path: ^1.9.0
  path_provider: ^2.1.2
  pine: ^1.0.3
  provider: ^6.1.2
  shared_preferences: ^2.2.2
  sqflite: ^2.3.3
  sqflite_common_ffi: ^2.3.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
